### PR TITLE
add vm_cluster_ocid as output

### PR DESCRIPTION
**Pull request by chanstev**
## Description
Add OCID of VM Cluster as output for further automation in OCI (e.g. DB Home creation)

## Type of Change

- [ ] Non-module change (e.g. CI/CD, documentation, etc.)
- [ ] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [x] Feature update backwards compatible feature updates.
  - [ ] Breaking changes.
  - [ ] Update to documentation

# Checklist

- [ ] I'm sure there are no other open Pull Requests for the same update/change
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings
- [ ] I did run all  [pre-commit](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/terraform-contribution-flow/#5-run-pre-commit-checks) checks

### CODE REVIEW

**Comment by chanstev** [comment]
@microsoft-github-policy-service agree

**Comment by sihbher** [comment]
Hi @chanstev, is this ocid property different than azapi_resource.odaa_vm_cluster.id?
If so, should you add "id" to the  response_export_values ? 

What I'd like to validate is if azapi_resource.odaa_vm_cluster.id still returns the id, did you test that?

**Comment by chanstev** [comment]
id returned azure's resource ID, while the OCID is the resource ID in OCI

**Comment by chanstev** [comment]
@sihbher will [terraform register version](https://registry.terraform.io/modules/Azure/avm-res-oracledatabase-cloudvmcluster/azurerm/0.1.0?tab=outputs) be reflected so that we can consume via `Azure/avm-res-oracledatabase-cloudvmcluster/azurerm ` with specific version,  instead of `github.com/Azure/terraform-azurerm-avm-res-oracledatabase-cloudvmcluster`?

**Pull request merged**
